server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 50000 # 연결 타임아웃 (밀리초)
        response-timeout: 60s  # 응답 타임아웃 (예: 10초)
      discovery:
        locator:
          enabled: true  # ??? ?????? ?? ???? ???? ??
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: JwtFilter
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/ticket-service/**
          filters:
            - StripPrefix=1
            - name: JwtFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - name: JwtFilter

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: "Spring Cloud Gateway Global Filter"
            preLogger: true
            postLogger: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web.reactive: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}